### PR TITLE
Add rpm and deb packaging files

### PR DESCRIPTION
**Pull request by ronan22**
* To easily distribute CAN devStudio, should have packaging file.

Signed-off-by: Ronan Le Martret <ronan.lemartret@iot.bzh>

### CODE REVIEW

**Comment by ronan22** [comment]
Yes, your're right, my mistake.

**Comment by gunnarx** [comment]
OK, now it looks good to me (but I'm not the project maintainer)

**Comment by rkollataj** [comment]
I was thinking about having CPack in the end for packaging. However since I am still thinking and you already did it I have nothing against accepting this PR :)

@ronan22 I have small request though. I am pretty close to v0.2 release. Could you change spec files from v0.1 to v0.2 already?

**Comment by rkollataj** [comment]
Closing since #108 implements similar functionality.

**Pull request closed without merging**
