### PR TITLE
CDS-73 Adds UIBackend engine and example usage

### PR DESCRIPTION
**Pull request by insooth**

### CODE REVIEW

**Comment by rkollataj** [comment]
Still not compiling with VS: https://ci.appveyor.com/project/rkollataj/candevstudio-qflna/build/1.0.228

**Comment by insooth** [comment]
Compiles under MSVC fine now.

**Comment by rkollataj** [comment]
Sorry this is too complicated to maintain. We will continue with dependency injection that is understandable for human beings :)

**Comment by insooth** [comment]
Well, I am a human being and I don't share that opinion :-) Presumably, asking questions in the review might help.

**Pull request closed without merging**
